### ISSUE TITLE
Fixes for memory errors

### ISSUE THREAD

**Issue by cscrimge** [mattreecebentley/plf_list#5]
I ran some tests of plf_list with GCC's `-fsanitize=undefined` and `-fsanitize=address`, and found a few issues:

- Check size to avoid performing a `memcpy` with a source pointer that might be null
- Use `std::memmove` over `std::memcpy` where ranges might overlap
- Avoid reading `groups.last_endpoint_group` when it might be out-of-bounds

[plf_sanitize.patch.txt](https://github.com/mattreecebentley/plf_list/files/1992446/plf_sanitize.patch.txt)

**Comment by mattreecebentley** [comment]
I appreciate you doing this,
The first one is annoying, but unfortunately true - apparently some compilers will bork if the source pointer is NULL, even if size == 0 (https://stackoverflow.com/questions/5243012/is-it-guaranteed-to-be-safe-to-perform-memcpy0-0-0). Fixed in most recent commit.
The second and third were already addressed in the last two commits a few days ago, so you must be using an older version than that.
The last is correct, I have fixed in most recent commit.
Once again, thanks for taking the time-
